"""Synthetic fixture tests: every line validates, and the interaction holds."""

from __future__ import annotations

from pathlib import Path

import pytest

from palimpsest_pipeline.adapters.base import to_ndjson_line
from palimpsest_pipeline.schema import validate_claim, validate_entity
from palimpsest_pipeline.synth import (
    THRESHOLD_LADDER,
    edge_counts_by_threshold,
    generate,
)

# The repo's committed synthetic fixture (regenerated by `synth --out`).
REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "fixtures" / "synthetic"


def test_generated_lines_validate_against_frozen_schema():
    # EXPECTATION: every generated entity validates against #/$defs/entityRecord
    # and every generated claim validates against the root schema — zero errors.
    entities, claims, _ = generate(scale=1)
    for e in entities:
        assert validate_entity(e.to_dict()) == []
    for c in claims:
        assert validate_claim(c.to_dict()) == []


def test_generated_lines_validate_at_higher_scale():
    entities, claims, _ = generate(scale=5)
    assert entities and claims
    for e in entities:
        assert validate_entity(e.to_dict()) == []
    for c in claims:
        assert validate_claim(c.to_dict()) == []


def test_every_anomaly_class_is_exercised():
    # EXPECTATION: generation exercises all five anomaly counters (>= 1 each).
    _, _, counters = generate(scale=1)
    d = counters.as_dict()
    for name, count in d.items():
        assert count >= 1, f"anomaly class {name} not exercised (={count})"


@pytest.mark.parametrize("scale", [1, 2, 5, 10])
def test_edge_count_monotonic_non_increasing_as_threshold_rises(scale):
    # EXPECTATION: as minConfidence rises across the ladder, the edge count never
    # increases, and it strictly decreases overall (first > last) — the signature
    # interaction (A5 / Q-6): reproduces the interaction, not the numbers.
    _, claims, _ = generate(scale=scale)
    counts = [n for _, n in edge_counts_by_threshold(claims)]
    assert counts == sorted(counts, reverse=True)  # non-increasing
    for lo, hi in zip(counts[1:], counts[:-1]):
        assert lo <= hi
    assert counts[0] > counts[-1]  # overall strict decrease


def test_committed_fixture_files_validate():
    # The fixture files committed in fixtures/synthetic/ must validate line-by-line
    # against the frozen contract (they are what CI / `make demo` consume).
    ent_path = FIXTURE_DIR / "entities.ndjson"
    claim_path = FIXTURE_DIR / "claims.ndjson"
    if not ent_path.is_file() or not claim_path.is_file():
        pytest.skip("fixture not generated yet (run: cli synth --out fixtures/synthetic)")
    import json

    for i, line in enumerate(ent_path.read_text().splitlines(), 1):
        if line.strip():
            assert validate_entity(json.loads(line)) == [], f"entities.ndjson:{i}"
    for i, line in enumerate(claim_path.read_text().splitlines(), 1):
        if line.strip():
            assert validate_claim(json.loads(line)) == [], f"claims.ndjson:{i}"


def test_serialization_is_byte_stable():
    # Regenerating produces identical bytes (deterministic canonical output).
    _, claims_a, _ = generate(scale=1)
    _, claims_b, _ = generate(scale=1)
    assert [to_ndjson_line(c) for c in claims_a] == [to_ndjson_line(c) for c in claims_b]
