/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/import/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rebuild-projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/undispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["undispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/supersede": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["supersede"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/merge-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["merge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["dispute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/assert-claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assertClaim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions/adjust-confidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["paths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/relation-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["relationTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportClaims"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["view"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["network"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{id}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["entityClaims"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{a}/relations/{b}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pair"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["random"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["claim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["evidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EnvelopeImportReportDto: {
            data?: components["schemas"]["ImportReportDto"];
            meta?: components["schemas"]["Meta"];
        };
        ImportReportDto: {
            run?: string;
            /** Format: int32 */
            batch?: number;
            /** Format: int32 */
            received?: number;
            /** Format: int32 */
            inserted?: number;
            /** Format: int32 */
            duplicates?: number;
            /** Format: int32 */
            superseded?: number;
            rejected?: components["schemas"]["RejectDto"][];
        };
        Meta: {
            requestId?: string;
            /** Format: int32 */
            count?: number;
            truncated?: boolean;
            counts?: components["schemas"]["NetworkCounts"];
            page?: components["schemas"]["Page"];
            asOfSystem?: string;
            statusFilter?: string;
        };
        NetworkCounts: {
            /** Format: int32 */
            possibly?: number;
            /** Format: int32 */
            certainly?: number;
            /** Format: int32 */
            undated?: number;
        };
        Page: {
            cursor?: string;
            /** Format: int32 */
            limit?: number;
            nextCursor?: string;
        };
        RejectDto: {
            /** Format: int32 */
            line?: number;
            reason?: string;
        };
        EnvelopeMapStringObject: {
            data?: {
                [key: string]: Record<string, never>;
            };
            meta?: components["schemas"]["Meta"];
        };
        UndisputeReq: {
            /** Format: int64 */
            claimId?: number;
        };
        JsonNode: Record<string, never>;
        SupersedeReq: {
            /** Format: int64 */
            claimId?: number;
            replacement?: components["schemas"]["JsonNode"];
            reason?: string;
        };
        MergeReq: {
            memberEntityIds?: number[];
            rationale?: string;
        };
        DisputeReq: {
            /** Format: int64 */
            claimId?: number;
            ground?: string;
            reason?: string;
        };
        AdjustReq: {
            /** Format: int64 */
            claimId?: number;
            confidence?: components["schemas"]["JsonNode"];
            reason?: string;
        };
        EnvelopeStatsDto: {
            data?: components["schemas"]["StatsDto"];
            meta?: components["schemas"]["Meta"];
        };
        HistogramBinDto: {
            band?: string;
            /** Format: int32 */
            count?: number;
        };
        SourceDto: {
            slug?: string;
            title?: string;
            version?: string;
            retrievalUri?: string;
            license?: string;
            licenseConfirmed?: boolean;
        };
        StatsDto: {
            entities?: {
                [key: string]: Record<string, never>;
            };
            claims?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int32 */
            sourceRecords?: number;
            sources?: components["schemas"]["SourceDto"][];
            confidenceHistogram?: components["schemas"]["HistogramBinDto"][];
            anomalyCounters?: {
                [key: string]: Record<string, never>;
            };
            gender?: {
                [key: string]: number;
            };
            temporalCodeShare?: {
                [key: string]: Record<string, never>;
            };
            /** Format: double */
            noRelationshipPct?: number;
        };
        EntitySummaryDto: {
            /** Format: int64 */
            id?: number;
            displayName?: string;
            entityType?: string;
            description?: string;
            gender?: string;
            lifeDates?: components["schemas"]["LifeDates"];
            /** Format: int32 */
            degreeScored?: number;
            /** Format: int32 */
            degreeUnscored?: number;
        };
        EnvelopeListEntitySummaryDto: {
            data?: components["schemas"]["EntitySummaryDto"][];
            meta?: components["schemas"]["Meta"];
        };
        LifeDates: {
            bornEarliest?: string;
            bornLatest?: string;
            diedEarliest?: string;
            diedLatest?: string;
        };
        EnvelopeListRunDto: {
            data?: components["schemas"]["RunDto"][];
            meta?: components["schemas"]["Meta"];
        };
        RunDto: {
            runId?: string;
            sourceSlug?: string;
            startedAt?: string;
            finishedAt?: string;
            /** Format: int32 */
            batches?: number;
            /** Format: int32 */
            received?: number;
            /** Format: int32 */
            inserted?: number;
            /** Format: int32 */
            duplicates?: number;
            /** Format: int32 */
            superseded?: number;
            /** Format: int32 */
            rejected?: number;
            manifest?: Record<string, never>;
        };
        EnvelopeRunDto: {
            data?: components["schemas"]["RunDto"];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopePathResult: {
            data?: components["schemas"]["PathResult"];
            meta?: components["schemas"]["Meta"];
        };
        PathResult: {
            paths?: components["schemas"]["PathStep"][][];
            budgetExceeded?: boolean;
            truncated?: boolean;
        };
        PathStep: {
            /** Format: int64 */
            entityId?: number;
            displayName?: string;
            /** Format: int64 */
            claimId?: number;
            /** Format: double */
            confidence?: number;
        };
        EnvelopeListSourceDto: {
            data?: components["schemas"]["SourceDto"][];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopeListRelationTypeDto: {
            data?: components["schemas"]["RelationTypeDto"][];
            meta?: components["schemas"]["Meta"];
        };
        RelationTypeDto: {
            slug?: string;
            label?: string;
            category?: string;
            rangeKind?: string;
            symmetric?: boolean;
        };
        AgentDto: {
            slug?: string;
            kind?: string;
            displayName?: string;
        };
        EnvelopeListAgentDto: {
            data?: components["schemas"]["AgentDto"][];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopeListEventDto: {
            data?: components["schemas"]["EventDto"][];
            meta?: components["schemas"]["Meta"];
        };
        EventDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            claimId?: number;
            eventType?: string;
            actor?: components["schemas"]["AgentDto"];
            occurredAt?: string;
            payload?: Record<string, never>;
        };
        AttributeGroupDto: {
            predicate?: string;
            claims?: components["schemas"]["ClaimDetailDto"][];
        };
        ClaimDetailDto: {
            /** Format: int64 */
            id?: number;
            subject?: components["schemas"]["EntitySummaryDto"];
            predicate?: string;
            object?: components["schemas"]["ObjectDto"];
            validTime?: components["schemas"]["FuzzyIntervalDto"];
            confidence?: components["schemas"]["ConfidenceDto"];
            method?: string;
            methodDetail?: Record<string, never>;
            status?: string;
            assertedBy?: components["schemas"]["AgentDto"];
            recordedAt?: string;
            importRunId?: string;
        };
        ConfidenceDto: {
            /** Format: double */
            effective?: number;
            origin?: string;
            raw?: Record<string, never>;
            calibrated?: boolean;
            scored?: boolean;
            band?: string;
        };
        CoverageDto: {
            bySource?: components["schemas"]["CoverageSourceDto"][];
            /** Format: int32 */
            scored?: number;
            /** Format: int32 */
            unscored?: number;
            calibration?: string;
        };
        CoverageSourceDto: {
            slug?: string;
            /** Format: int32 */
            relationshipClaims?: number;
            /** Format: int32 */
            attributeClaims?: number;
        };
        EntityViewDto: {
            summary?: components["schemas"]["EntitySummaryDto"];
            externalIds?: components["schemas"]["ExternalIdDto"][];
            attributeClaims?: components["schemas"]["AttributeGroupDto"][];
            coverage?: components["schemas"]["CoverageDto"];
        };
        EnvelopeEntityViewDto: {
            data?: components["schemas"]["EntityViewDto"];
            meta?: components["schemas"]["Meta"];
        };
        ExternalIdDto: {
            authority?: string;
            externalId?: string;
        };
        FuzzyIntervalDto: {
            startEarliest?: string;
            startLatest?: string;
            endEarliest?: string;
            endLatest?: string;
            approximate?: boolean;
            original?: Record<string, never>;
        };
        LiteralDto: {
            kind?: string;
            value?: Record<string, never>;
            authority?: string;
        };
        ObjectDto: {
            entity?: components["schemas"]["EntitySummaryDto"];
            literal?: components["schemas"]["LiteralDto"];
        };
        EdgeDto: {
            /** Format: int64 */
            claimId?: number;
            counterpart?: components["schemas"]["EntitySummaryDto"];
            predicate?: string;
            confidence?: components["schemas"]["ConfidenceDto"];
            validTime?: components["schemas"]["FuzzyIntervalDto"];
            scored?: boolean;
            certainlyActive?: boolean;
            undated?: boolean;
            status?: string;
        };
        EnvelopeNetworkDto: {
            data?: components["schemas"]["NetworkDto"];
            meta?: components["schemas"]["Meta"];
        };
        NetworkDto: {
            focus?: components["schemas"]["EntitySummaryDto"];
            edges?: components["schemas"]["EdgeDto"][];
        };
        EnvelopeListClaimDetailDto: {
            data?: components["schemas"]["ClaimDetailDto"][];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopePairDossierDto: {
            data?: components["schemas"]["PairDossierDto"];
            meta?: components["schemas"]["Meta"];
        };
        PairDossierDto: {
            a?: components["schemas"]["EntitySummaryDto"];
            b?: components["schemas"]["EntitySummaryDto"];
            claims?: components["schemas"]["ClaimDetailDto"][];
        };
        EnvelopeEntitySummaryDto: {
            data?: components["schemas"]["EntitySummaryDto"];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopeClaimDetailDto: {
            data?: components["schemas"]["ClaimDetailDto"];
            meta?: components["schemas"]["Meta"];
        };
        EnvelopeHistoryDto: {
            data?: components["schemas"]["HistoryDto"];
            meta?: components["schemas"]["Meta"];
        };
        HistoryDto: {
            events?: components["schemas"]["EventDto"][];
        };
        EnvelopeEvidenceDto: {
            data?: components["schemas"]["EvidenceDto"];
            meta?: components["schemas"]["Meta"];
        };
        EvidenceDto: {
            claim?: components["schemas"]["ClaimDetailDto"];
            support?: components["schemas"]["SupportDto"][];
        };
        SourceRecordDto: {
            recordKind?: string;
            externalId?: string;
            contentHash?: string;
            raw?: Record<string, never>;
        };
        SupportDto: {
            source?: components["schemas"]["SourceDto"];
            record?: components["schemas"]["SourceRecordDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    batch: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeImportReportDto"];
                };
            };
        };
    };
    rebuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    undispute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndisputeReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    supersede: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupersedeReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    merge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    dispute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    assertClaim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    adjust: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeMapStringObject"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeStatsDto"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                type?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListEntitySummaryDto"];
                };
            };
        };
    };
    runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListRunDto"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeRunDto"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    readyz_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    paths: {
        parameters: {
            query: {
                from: number;
                to: number;
                minConfidence?: number;
                windowStart?: string;
                windowEnd?: string;
                temporalMode?: string;
                maxDepth?: number;
                maxPaths?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopePathResult"];
                };
            };
        };
    };
    sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListSourceDto"];
                };
            };
        };
    };
    relationTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListRelationTypeDto"];
                };
            };
        };
    };
    agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListAgentDto"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    healthz_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    exportClaims: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                since?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListEventDto"];
                };
            };
        };
    };
    view: {
        parameters: {
            query?: {
                resolution?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeEntityViewDto"];
                };
            };
        };
    };
    network: {
        parameters: {
            query?: {
                minConfidence?: number;
                windowStart?: string;
                windowEnd?: string;
                temporalMode?: string;
                includeUnscored?: boolean;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeNetworkDto"];
                };
            };
        };
    };
    entityClaims: {
        parameters: {
            query?: {
                predicate?: string;
                role?: string;
                status?: string;
                minConfidence?: number;
                includeUnscored?: boolean;
                windowStart?: string;
                windowEnd?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeListClaimDetailDto"];
                };
            };
        };
    };
    pair: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path: {
                a: number;
                b: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopePairDossierDto"];
                };
            };
        };
    };
    random: {
        parameters: {
            query?: {
                type?: string;
                minScoredDegree?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeEntitySummaryDto"];
                };
            };
        };
    };
    lookup: {
        parameters: {
            query: {
                authority: string;
                externalId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeEntitySummaryDto"];
                };
            };
        };
    };
    claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeClaimDetailDto"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeHistoryDto"];
                };
            };
        };
    };
    evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EnvelopeEvidenceDto"];
                };
            };
        };
    };
}
