#!/usr/bin/env bash
# Install the pre-commit hard-gate hooks (no-dump, no-Ingress). Idempotent.
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
HOOK="$REPO/.git/hooks/pre-commit"
mkdir -p "$REPO/.git/hooks"
cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# PALIMPSEST hard gates (generated by scripts/install_hooks.sh). Do not edit here;
# edit scripts/check_no_dump.sh / scripts/check_no_ingress.sh.
set -euo pipefail
REPO="$(git rev-parse --show-toplevel)"
bash "$REPO/scripts/check_no_dump.sh" staged
bash "$REPO/scripts/check_no_ingress.sh" staged
EOF
chmod +x "$HOOK"
echo "installed pre-commit hook → $HOOK"
